package entity;
// Generated Apr 12, 2018 1:14:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Deposit generated by hbm2java
 */
public class Deposit  implements java.io.Serializable {


     private Integer depId;
     private AccountInfo accountInfo;
     private double deposit;
     private Date ddate;
     private Set transactionAccounts = new HashSet(0);

    public Deposit() {
    }

	
    public Deposit(AccountInfo accountInfo, double deposit, Date ddate) {
        this.accountInfo = accountInfo;
        this.deposit = deposit;
        this.ddate = ddate;
    }
    public Deposit(AccountInfo accountInfo, double deposit, Date ddate, Set transactionAccounts) {
       this.accountInfo = accountInfo;
       this.deposit = deposit;
       this.ddate = ddate;
       this.transactionAccounts = transactionAccounts;
    }
   
    public Integer getDepId() {
        return this.depId;
    }
    
    public void setDepId(Integer depId) {
        this.depId = depId;
    }
    public AccountInfo getAccountInfo() {
        return this.accountInfo;
    }
    
    public void setAccountInfo(AccountInfo accountInfo) {
        this.accountInfo = accountInfo;
    }
    public double getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(double deposit) {
        this.deposit = deposit;
    }
    public Date getDdate() {
        return this.ddate;
    }
    
    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }
    public Set getTransactionAccounts() {
        return this.transactionAccounts;
    }
    
    public void setTransactionAccounts(Set transactionAccounts) {
        this.transactionAccounts = transactionAccounts;
    }




}


