package entity;
// Generated Apr 12, 2018 1:14:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LoanPayment generated by hbm2java
 */
public class LoanPayment  implements java.io.Serializable {


     private Integer payId;
     private AccountInfo accountInfo;
     private Loan loan;
     private int payMonth;
     private double payAmount;
     private Date pdate;

    public LoanPayment() {
    }

    public LoanPayment(AccountInfo accountInfo, Loan loan, int payMonth, double payAmount, Date pdate) {
       this.accountInfo = accountInfo;
       this.loan = loan;
       this.payMonth = payMonth;
       this.payAmount = payAmount;
       this.pdate = pdate;
    }
   
    public Integer getPayId() {
        return this.payId;
    }
    
    public void setPayId(Integer payId) {
        this.payId = payId;
    }
    public AccountInfo getAccountInfo() {
        return this.accountInfo;
    }
    
    public void setAccountInfo(AccountInfo accountInfo) {
        this.accountInfo = accountInfo;
    }
    public Loan getLoan() {
        return this.loan;
    }
    
    public void setLoan(Loan loan) {
        this.loan = loan;
    }
    public int getPayMonth() {
        return this.payMonth;
    }
    
    public void setPayMonth(int payMonth) {
        this.payMonth = payMonth;
    }
    public double getPayAmount() {
        return this.payAmount;
    }
    
    public void setPayAmount(double payAmount) {
        this.payAmount = payAmount;
    }
    public Date getPdate() {
        return this.pdate;
    }
    
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }




}


