package entity;
// Generated Apr 12, 2018 1:14:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Loan generated by hbm2java
 */
public class Loan  implements java.io.Serializable {


     private Integer loanId;
     private AccountInfo accountInfo;
     private double loanAmount;
     private int interestRate;
     private int totalMonth;
     private double totalPayable;
     private double monthlyPayment;
     private Date ldate;
     private Set loanPayments = new HashSet(0);

    public Loan() {
    }

	
    public Loan(AccountInfo accountInfo, double loanAmount, int interestRate, int totalMonth, double totalPayable, double monthlyPayment, Date ldate) {
        this.accountInfo = accountInfo;
        this.loanAmount = loanAmount;
        this.interestRate = interestRate;
        this.totalMonth = totalMonth;
        this.totalPayable = totalPayable;
        this.monthlyPayment = monthlyPayment;
        this.ldate = ldate;
    }
    public Loan(AccountInfo accountInfo, double loanAmount, int interestRate, int totalMonth, double totalPayable, double monthlyPayment, Date ldate, Set loanPayments) {
       this.accountInfo = accountInfo;
       this.loanAmount = loanAmount;
       this.interestRate = interestRate;
       this.totalMonth = totalMonth;
       this.totalPayable = totalPayable;
       this.monthlyPayment = monthlyPayment;
       this.ldate = ldate;
       this.loanPayments = loanPayments;
    }
   
    public Integer getLoanId() {
        return this.loanId;
    }
    
    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }
    public AccountInfo getAccountInfo() {
        return this.accountInfo;
    }
    
    public void setAccountInfo(AccountInfo accountInfo) {
        this.accountInfo = accountInfo;
    }
    public double getLoanAmount() {
        return this.loanAmount;
    }
    
    public void setLoanAmount(double loanAmount) {
        this.loanAmount = loanAmount;
    }
    public int getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(int interestRate) {
        this.interestRate = interestRate;
    }
    public int getTotalMonth() {
        return this.totalMonth;
    }
    
    public void setTotalMonth(int totalMonth) {
        this.totalMonth = totalMonth;
    }
    public double getTotalPayable() {
        return this.totalPayable;
    }
    
    public void setTotalPayable(double totalPayable) {
        this.totalPayable = totalPayable;
    }
    public double getMonthlyPayment() {
        return this.monthlyPayment;
    }
    
    public void setMonthlyPayment(double monthlyPayment) {
        this.monthlyPayment = monthlyPayment;
    }
    public Date getLdate() {
        return this.ldate;
    }
    
    public void setLdate(Date ldate) {
        this.ldate = ldate;
    }
    public Set getLoanPayments() {
        return this.loanPayments;
    }
    
    public void setLoanPayments(Set loanPayments) {
        this.loanPayments = loanPayments;
    }




}


