package entity;
// Generated Apr 12, 2018 1:14:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transfer generated by hbm2java
 */
public class Transfer  implements java.io.Serializable {


     private Integer transferId;
     private AccountInfo accountInfo;
     private int transferAccount;
     private double transferAmount;
     private Date tdate;
     private Set transactionAccounts = new HashSet(0);

    public Transfer() {
    }

	
    public Transfer(AccountInfo accountInfo, int transferAccount, double transferAmount, Date tdate) {
        this.accountInfo = accountInfo;
        this.transferAccount = transferAccount;
        this.transferAmount = transferAmount;
        this.tdate = tdate;
    }
    public Transfer(AccountInfo accountInfo, int transferAccount, double transferAmount, Date tdate, Set transactionAccounts) {
       this.accountInfo = accountInfo;
       this.transferAccount = transferAccount;
       this.transferAmount = transferAmount;
       this.tdate = tdate;
       this.transactionAccounts = transactionAccounts;
    }
   
    public Integer getTransferId() {
        return this.transferId;
    }
    
    public void setTransferId(Integer transferId) {
        this.transferId = transferId;
    }
    public AccountInfo getAccountInfo() {
        return this.accountInfo;
    }
    
    public void setAccountInfo(AccountInfo accountInfo) {
        this.accountInfo = accountInfo;
    }
    public int getTransferAccount() {
        return this.transferAccount;
    }
    
    public void setTransferAccount(int transferAccount) {
        this.transferAccount = transferAccount;
    }
    public double getTransferAmount() {
        return this.transferAmount;
    }
    
    public void setTransferAmount(double transferAmount) {
        this.transferAmount = transferAmount;
    }
    public Date getTdate() {
        return this.tdate;
    }
    
    public void setTdate(Date tdate) {
        this.tdate = tdate;
    }
    public Set getTransactionAccounts() {
        return this.transactionAccounts;
    }
    
    public void setTransactionAccounts(Set transactionAccounts) {
        this.transactionAccounts = transactionAccounts;
    }




}


