package entity;
// Generated Apr 12, 2018 1:14:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TransactionAccount generated by hbm2java
 */
public class TransactionAccount  implements java.io.Serializable {


     private Integer transactionId;
     private AccountInfo accountInfo;
     private Deposit deposit;
     private Transfer transfer;
     private Withdrawal withdrawal;
     private Double deposit_1;
     private Date ddate;
     private Double withdraw;
     private Date wdate;
     private Double transferAmount;
     private Integer transferAccount;
     private Date tdate;

    public TransactionAccount() {
    }

	
    public TransactionAccount(AccountInfo accountInfo) {
        this.accountInfo = accountInfo;
    }
    public TransactionAccount(AccountInfo accountInfo, Deposit deposit, Transfer transfer, Withdrawal withdrawal, Double deposit_1, Date ddate, Double withdraw, Date wdate, Double transferAmount, Integer transferAccount, Date tdate) {
       this.accountInfo = accountInfo;
       this.deposit = deposit;
       this.transfer = transfer;
       this.withdrawal = withdrawal;
       this.deposit_1 = deposit_1;
       this.ddate = ddate;
       this.withdraw = withdraw;
       this.wdate = wdate;
       this.transferAmount = transferAmount;
       this.transferAccount = transferAccount;
       this.tdate = tdate;
    }
   
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }
    public AccountInfo getAccountInfo() {
        return this.accountInfo;
    }
    
    public void setAccountInfo(AccountInfo accountInfo) {
        this.accountInfo = accountInfo;
    }
    public Deposit getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(Deposit deposit) {
        this.deposit = deposit;
    }
    public Transfer getTransfer() {
        return this.transfer;
    }
    
    public void setTransfer(Transfer transfer) {
        this.transfer = transfer;
    }
    public Withdrawal getWithdrawal() {
        return this.withdrawal;
    }
    
    public void setWithdrawal(Withdrawal withdrawal) {
        this.withdrawal = withdrawal;
    }
    public Double getDeposit_1() {
        return this.deposit_1;
    }
    
    public void setDeposit_1(Double deposit_1) {
        this.deposit_1 = deposit_1;
    }
    public Date getDdate() {
        return this.ddate;
    }
    
    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }
    public Double getWithdraw() {
        return this.withdraw;
    }
    
    public void setWithdraw(Double withdraw) {
        this.withdraw = withdraw;
    }
    public Date getWdate() {
        return this.wdate;
    }
    
    public void setWdate(Date wdate) {
        this.wdate = wdate;
    }
    public Double getTransferAmount() {
        return this.transferAmount;
    }
    
    public void setTransferAmount(Double transferAmount) {
        this.transferAmount = transferAmount;
    }
    public Integer getTransferAccount() {
        return this.transferAccount;
    }
    
    public void setTransferAccount(Integer transferAccount) {
        this.transferAccount = transferAccount;
    }
    public Date getTdate() {
        return this.tdate;
    }
    
    public void setTdate(Date tdate) {
        this.tdate = tdate;
    }




}


