package entity;
// Generated Apr 12, 2018 1:14:00 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private AccountInfo accountInfo;
     private String name;
     private String email;
     private String userName;
     private String password;
     private String userRole;

    public User() {
    }

	
    public User(AccountInfo accountInfo, String name, String email, String userName, String password) {
        this.accountInfo = accountInfo;
        this.name = name;
        this.email = email;
        this.userName = userName;
        this.password = password;
    }
    public User(AccountInfo accountInfo, String name, String email, String userName, String password, String userRole) {
       this.accountInfo = accountInfo;
       this.name = name;
       this.email = email;
       this.userName = userName;
       this.password = password;
       this.userRole = userRole;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AccountInfo getAccountInfo() {
        return this.accountInfo;
    }
    
    public void setAccountInfo(AccountInfo accountInfo) {
        this.accountInfo = accountInfo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }




}


