package entity;
// Generated Apr 12, 2018 1:14:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Withdrawal generated by hbm2java
 */
public class Withdrawal  implements java.io.Serializable {


     private Integer withdrawId;
     private AccountInfo accountInfo;
     private double withdraw;
     private Date wdate;
     private Set transactionAccounts = new HashSet(0);

    public Withdrawal() {
    }

	
    public Withdrawal(AccountInfo accountInfo, double withdraw, Date wdate) {
        this.accountInfo = accountInfo;
        this.withdraw = withdraw;
        this.wdate = wdate;
    }
    public Withdrawal(AccountInfo accountInfo, double withdraw, Date wdate, Set transactionAccounts) {
       this.accountInfo = accountInfo;
       this.withdraw = withdraw;
       this.wdate = wdate;
       this.transactionAccounts = transactionAccounts;
    }
   
    public Integer getWithdrawId() {
        return this.withdrawId;
    }
    
    public void setWithdrawId(Integer withdrawId) {
        this.withdrawId = withdrawId;
    }
    public AccountInfo getAccountInfo() {
        return this.accountInfo;
    }
    
    public void setAccountInfo(AccountInfo accountInfo) {
        this.accountInfo = accountInfo;
    }
    public double getWithdraw() {
        return this.withdraw;
    }
    
    public void setWithdraw(double withdraw) {
        this.withdraw = withdraw;
    }
    public Date getWdate() {
        return this.wdate;
    }
    
    public void setWdate(Date wdate) {
        this.wdate = wdate;
    }
    public Set getTransactionAccounts() {
        return this.transactionAccounts;
    }
    
    public void setTransactionAccounts(Set transactionAccounts) {
        this.transactionAccounts = transactionAccounts;
    }




}


